
import java.awt.Color;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author tijan_000
 */
public class Matrix2x2Form extends javax.swing.JFrame {

    /**
     * Creates new form Matrix2x2Form
     */
    public Matrix2x2Form() {
        initComponents();
        getContentPane().setBackground(Color.PINK);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        a11numberText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        a12numberText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        a21numberText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        a22numberText = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        b11numberText = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        b12numberText = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        b21numberText = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        b22numberText = new javax.swing.JTextField();
        SabiranjeMatricaButton = new javax.swing.JButton();
        OduzimanjeMatricaButton = new javax.swing.JButton();
        MnozenjeMatricaButton = new javax.swing.JButton();
        RezultatLabel = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ResenjeLabel1 = new javax.swing.JLabel();
        ResenjeLabel2 = new javax.swing.JLabel();
        ResenjeLabel3 = new javax.swing.JLabel();
        ResenjeLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setTitle("Matrix2x2\n");
        setMaximumSize(null);
        setPreferredSize(new java.awt.Dimension(450, 450));
        setResizable(false);

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("a11");

        jLabel2.setText("a12");

        jLabel3.setText("a21");

        jLabel4.setText("a22");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(a11numberText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(a21numberText)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(a12numberText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(a22numberText)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(a11numberText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(a12numberText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(a21numberText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(a22numberText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setText(" b11");

        jLabel6.setText("b12");

        jLabel7.setText(" b21");

        jLabel8.setText("b22");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b11numberText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b21numberText)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b12numberText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b22numberText)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(b11numberText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(b12numberText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(b21numberText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(b22numberText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        SabiranjeMatricaButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        SabiranjeMatricaButton.setText("+");
        SabiranjeMatricaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SabiranjeMatricaButtonActionPerformed(evt);
            }
        });

        OduzimanjeMatricaButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        OduzimanjeMatricaButton.setText("-");
        OduzimanjeMatricaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OduzimanjeMatricaButtonActionPerformed(evt);
            }
        });

        MnozenjeMatricaButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        MnozenjeMatricaButton.setText("*");
        MnozenjeMatricaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnozenjeMatricaButtonActionPerformed(evt);
            }
        });

        RezultatLabel.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        RezultatLabel.setText("Rezultat je:");

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Y, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setText("About Matrix2x2");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MnozenjeMatricaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SabiranjeMatricaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(OduzimanjeMatricaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(ResenjeLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(ResenjeLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ResenjeLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(ResenjeLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addComponent(jLabel10))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RezultatLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(SabiranjeMatricaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(RezultatLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ResenjeLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ResenjeLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ResenjeLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ResenjeLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(OduzimanjeMatricaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(18, 18, 18)
                .addComponent(MnozenjeMatricaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SabiranjeMatricaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SabiranjeMatricaButtonActionPerformed
        int number1, number2, number3, number4, number5, number6, number7, number8;
        try {
            number1 = Integer.parseInt(
                    this.a11numberText.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Wrong number a11", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            number2 = Integer.parseInt(
                    this.a12numberText.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Wrong number a12", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            number3 = Integer.parseInt(
                    this.a21numberText.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Wrong number a21", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            number4 = Integer.parseInt(
                    this.a22numberText.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Wrong number a22", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            number5 = Integer.parseInt(
                    this.b11numberText.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Wrong number b11", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            number6 = Integer.parseInt(
                    this.b12numberText.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Wrong number b12", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            number7 = Integer.parseInt(
                    this.b21numberText.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Wrong number b21", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            number8 = Integer.parseInt(
                    this.b22numberText.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Wrong number b22", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int Rezultat = number1 + number5;
        this.ResenjeLabel1.setText(
                " " + Rezultat);

        int Rezultat1 = number2 + number6;
        this.ResenjeLabel2.setText(
                " " + Rezultat1);

        int Rezultat2 = number3 + number7;
        this.ResenjeLabel3.setText(
                " " + Rezultat2);

        int Rezultat3 = number4 + number8;
        this.ResenjeLabel4.setText(
                " " + Rezultat3);

    }//GEN-LAST:event_SabiranjeMatricaButtonActionPerformed

    private void OduzimanjeMatricaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OduzimanjeMatricaButtonActionPerformed
        int number1, number2, number3, number4, number5, number6, number7, number8;
        try {
            number1 = Integer.parseInt(
                    this.a11numberText.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Wrong number a11", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            number2 = Integer.parseInt(
                    this.a12numberText.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Wrong number a12", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            number3 = Integer.parseInt(
                    this.a21numberText.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Wrong number a21", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            number4 = Integer.parseInt(
                    this.a22numberText.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Wrong number a22", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            number5 = Integer.parseInt(
                    this.b11numberText.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Wrong number b11", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            number6 = Integer.parseInt(
                    this.b12numberText.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Wrong number b12", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            number7 = Integer.parseInt(
                    this.b21numberText.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Wrong number b21", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            number8 = Integer.parseInt(
                    this.b22numberText.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Wrong number b22", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int Rezultat = number1 - number5;
        this.ResenjeLabel1.setText(
                " " + Rezultat);

        int Rezultat1 = number2 - number6;
        this.ResenjeLabel2.setText(
                " " + Rezultat1);

        int Rezultat2 = number3 - number7;
        this.ResenjeLabel3.setText(
                " " + Rezultat2);

        int Rezultat3 = number4 - number8;
        this.ResenjeLabel4.setText(
                " " + Rezultat3);

    }//GEN-LAST:event_OduzimanjeMatricaButtonActionPerformed

    private void MnozenjeMatricaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnozenjeMatricaButtonActionPerformed
        int number1, number2, number3, number4, number5, number6, number7, number8;
        try {
            number1 = Integer.parseInt(
                    this.a11numberText.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Wrong number a11", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            number2 = Integer.parseInt(
                    this.a12numberText.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Wrong number a12", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            number3 = Integer.parseInt(
                    this.a21numberText.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Wrong number a21", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            number4 = Integer.parseInt(
                    this.a22numberText.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Wrong number a22", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            number5 = Integer.parseInt(
                    this.b11numberText.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Wrong number b11", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            number6 = Integer.parseInt(
                    this.b12numberText.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Wrong number b12", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            number7 = Integer.parseInt(
                    this.b21numberText.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Wrong number b21", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            number8 = Integer.parseInt(
                    this.b22numberText.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Wrong number b22", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int Rezultat = (number1 * number5) + (number2 * number7);
        this.ResenjeLabel1.setText(
                " " + Rezultat);
        int Rezultat1 = (number1 * number6) + (number2 * number8);
        this.ResenjeLabel2.setText(
                " " + Rezultat1);
        int Rezultat2 = (number3 * number5) + (number4 * number7);
        this.ResenjeLabel3.setText(
                " " + Rezultat2);
        int Rezultat3 = (number3 * number6) + (number4 * number8);
        this.ResenjeLabel4.setText(
                " " + Rezultat3);


    }//GEN-LAST:event_MnozenjeMatricaButtonActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        new AboutMatrix2x2Form().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Matrix2x2Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Matrix2x2Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Matrix2x2Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Matrix2x2Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Matrix2x2Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MnozenjeMatricaButton;
    private javax.swing.JButton OduzimanjeMatricaButton;
    private javax.swing.JLabel ResenjeLabel1;
    private javax.swing.JLabel ResenjeLabel2;
    private javax.swing.JLabel ResenjeLabel3;
    private javax.swing.JLabel ResenjeLabel4;
    private javax.swing.JLabel RezultatLabel;
    private javax.swing.JButton SabiranjeMatricaButton;
    private javax.swing.JTextField a11numberText;
    private javax.swing.JTextField a12numberText;
    private javax.swing.JTextField a21numberText;
    private javax.swing.JTextField a22numberText;
    private javax.swing.JTextField b11numberText;
    private javax.swing.JTextField b12numberText;
    private javax.swing.JTextField b21numberText;
    private javax.swing.JTextField b22numberText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
